export enum Genre {
  COMPOSITE = "COMPOSITE",
  PLAY = "PLAY",
  MUSICAL = "MUSICAL",
  POP_DANCE = "POP_DANCE",
  POP_MUSIC = "POP_MUSIC",
  CLASSICAL_MUSIC = "CLASSICAL_MUSIC",
  KOREAN_MUSIC = "KOREAN_MUSIC",
  CIRCUS_MAGIC = "CIRCUS_MAGIC",
  DANCE = "DANCE",
}
