export const PATH = {
  HOME: "/home",
  PLAYROOM: "/playroom",
  SELECT_PERFORMANCE: "/playroom/select-performance",
  CHILD_DATE_SELECTION: "/playroom/child-date-selection",
  REVIEW_WRITING: "/playroom/review-writing",
  VOICE_REVIEW: "/playroom/voice-review",
  CHAR_TYPE: "/playroom/character-type-select",
  CHAR_EMOTION: "/playroom/character-emotion-select",
  CHAR_ACCESSORY: "/playroom/character-acc-select",
  CHAR_PREV: "/playroom/character-preview",
  WISHLIST: "/favorites",
  PROFILE: "/mypage",
  MEMBER_INFO: "/member-info",
  CHILD_INFO: "/child-info",
  STORY_VILLAGE_BOOK: "/story-village-book",
  PERFORMANCE_DETAIL: (performanceId: number) =>
    `/performances/${performanceId}` as const,

  SIGNUP: "/signup",
  REGION_REGISTRATION: "/region-registration",
  CHILD_REGISTRATION: "/child-registration",
  LOGIN_REDIRECT: "/login-redirect",
  LOGIN: "/login",
} as const;
