export const ENV_KEYS = {
  // Database
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
  PORT: 'PORT',

  // Node
  NODE_ENV: 'NODE_ENV',

  // TypeORM
  TYPEORM_SYNCHRONIZE: 'TYPEORM_SYNCHRONIZE',
  TYPEORM_LOGGING: 'TYPEORM_LOGGING',
  // AWS
  AWS_ENDPOINT: 'AWS_ENDPOINT',
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY: 'AWS_ACCESS_KEY',
  AWS_SECRET_KEY: 'AWS_SECRET_KEY',
  AWS_S3_BUCKET: 'AWS_S3_BUCKET',
} as const;
