export const ENV_KEYS = {
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  TYPEORM_SYNCHRONIZE: 'TYPEORM_SYNCHRONIZE',
  TYPEORM_LOGGING: 'TYPEORM_LOGGING',
} as const;
