export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum Profile {
  DOG = "DOG",
  CAT = "CAT",
  DINOSAUR = "DINOSAUR",
  RABBIT = "RABBIT",
  CHICK = "CHICK",
}

export enum Genre {
  PLAY = "PLAY",
  PERFORMANCE = "PERFORMANCE",
  MUSICAL = "MUSICAL",
  CIRCUS = "CIRCUS",
  MAGIC = "MAGIC",
}

export enum Trait {
  MUSIC_LOVER = "MUSIC_LOVER",
  SOUND_SENSITIVE = "SOUND_SENSITIVE",
  ACTIVE = "ACTIVE",
  SHORT_ATTENTION = "SHORT_ATTENTION",
}

export enum Sido {
  SEOUL = "SEOUL",
  GYEONGGI = "GYEONGGI",
  JEON_BUK = "JEON_BUK",
  JEON_NAM = "JEON_NAM",
  CHUNG_BUK = "CHUNG_BUK",
  CHUNG_NAM = "CHUNG_NAM",
  GYEONG_BUK = "GYEONG_BUK",
  GYEONG_NAM = "GYEONG_NAM",

  BUSAN = "BUSAN",
  DAEGU = "DAEGU",
  INCHEON = "INCHEON",
  GWANGJU = "GWANGJU",
  DAEJEON = "DAEJEON",
  ULSAN = "ULSAN",
}

export enum Role {
  USER = "USER",
  ADMIN = "ADMIN",
  TEMP = "TEMP",
}
