export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum Profile {
  DOG = "DOG",
  CAT = "CAT",
  DINOSAUR = "DINOSAUR",
  RABBIT = "RABBIT",
  CHICK = "CHICK",
}

export enum Genre {
  COMPOSITE = "COMPOSITE",
  PLAY = "PLAY",
  MUSICAL = "MUSICAL",
  POP_DANCE = "POP_DANCE",
  POP_MUSIC = "POP_MUSIC",
  CLASSICAL_MUSIC = "CLASSICAL_MUSIC",
  KOREAN_MUSIC = "KOREAN_MUSIC",
  CIRCUS_MAGIC = "CIRCUS_MAGIC",
  DANCE = "DANCE",
}

export enum Trait {
  MUSIC_LOVER = "MUSIC_LOVER",
  DANCE_LOVER = "DANCE_LOVER",
  SOUND_SENSITIVE = "SOUND_SENSITIVE",
  ACTIVE = "ACTIVE",
  SHORT_ATTENTION = "SHORT_ATTENTION",
}

export enum Sido {
  SEOUL = "SEOUL",
  GYEONGGI = "GYEONGGI",
  GANGWON = "GANGWON",
  CHUNGCHEONG = "CHUNGCHEONG",
  JEOLLA = "JEOLLA",
  GYEONGSANG = "GYEONGSANG",
  JEJU = "JEJU",
}

export enum Role {
  USER = "USER",
  ADMIN = "ADMIN",
  TEMP = "TEMP",
}
