import { PATH } from "@/shared/constants";

export const REVIEW_FLOW = [
  PATH.SELECT_PERFORMANCE,
  PATH.CHILD_DATE_SELECTION,
  PATH.REVIEW_WRITING,
  // PATH.VOICE_REVIEW,

  PATH.CHAR_TYPE,
  PATH.CHAR_ACCESSORY,
  PATH.REVIEW_WRITING,
  PATH.VOICE_REVIEW,
];
